name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: |
        cd src
        npm install

    - name: Build
      run: |
        cd src
        npm run build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v2
      with:
        name: production-build
        path: javascript/
